# Generated by Django 4.2.5 on 2023-09-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0002_music_musictrack_delete_musictrackmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="music",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="musictrack",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="music",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="player.artist",
            ),
        ),
    ]
