# Generated by Django 4.2.5 on 2023-09-25 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player",
         "0003_artist_alter_music_title_alter_musictrack_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "title",
                    models.CharField(max_length=100,
                                     primary_key=True,
                                     serialize=False),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="player.artist"),
                ),
            ],
        ),
    ]
