# Generated by Django 4.2.5 on 2023-09-27 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0004_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="player.album",
            ),
        ),
    ]
