# Generated by Django 4.2.5 on 2023-10-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0004_add_song_opinion_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="opiniononsong",
            name="opinion",
            field=models.CharField(
                choices=[("1", "Like"), ("0", "NoOpinion"), ("-1", "DisLike")],
                default="0",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
