# Generated by Django 4.2.5 on 2023-09-27 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0005_add_model_to_music"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music",
            name="artist",
        ),
    ]
