# Generated by Django 4.2.5 on 2023-09-27 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player",
         "0006_remove_artist_from_music_now_switched_to_album_s_artist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="player.album"),
        ),
    ]
