# Generated by Django 4.2.5 on 2023-09-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0007_Music_DOT_album__now_NOT_NULL_constained"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="id",
            field=models.BigIntegerField(auto_created=True, null=True),
        ),
    ]
