# Generated by Django 4.2.5 on 2023-10-11 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0007_playlist_playlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistitem",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="player.musictrack",
            ),
        ),
    ]
