# Generated by Django 4.2.5 on 2023-09-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0008_album_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, default=0, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="album",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
