# Generated by Django 4.2.5 on 2023-09-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0009_alter_album_id_alter_album_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
